"""add file attachment columns to papers

Revision ID: 1f23b8a31613
Revises: d6a1c8e00104
Create Date: 2026-07-26 17:27:38.721854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f23b8a31613'
down_revision: Union[str, Sequence[str], None] = 'd6a1c8e00104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('file_storage_key', sa.String(length=500), nullable=True))
    op.add_column('papers', sa.Column('file_original_name', sa.String(length=500), nullable=True))
    op.add_column('papers', sa.Column('file_size_bytes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'file_size_bytes')
    op.drop_column('papers', 'file_original_name')
    op.drop_column('papers', 'file_storage_key')
    # ### end Alembic commands ###
