"""add owner_id to papers

Revision ID: d6a1c8e00104
Revises: 14f525a024fe
Create Date: 2026-07-25 22:47:32.999814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a1c8e00104'
down_revision: Union[str, Sequence[str], None] = '14f525a024fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('owner_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_papers_owner_id'), 'papers', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_owner_id'), table_name='papers')
    op.drop_column('papers', 'owner_id')
    # ### end Alembic commands ###
